Remove explicit region assigning
VerdigrisTech/spark-cassandra-connection-factory pull request #1
Opened 2019-03-13 07:51 UTC by Lance0312

SparkConf is intended for passing configuration to
driver, and driver would not pass those configuration
to executors. Thus, using this factory in a multi
node spark cluster would result in error.

User must set AWS region through environment variable
AWS_REGION.

2019-03-14 06:51 UTC, danielscw approved these changes
LGTM

2019-04-02 22:54 UTC, AndrewJo requested changes
Seems like you bumped the minor version for this change. However, this change breaks backwards compatibility and violates sementic versioning (minor version increment introduces a new feature without breaking existing functionality). Since this is an open source package, I think we need to be a little bit more careful than haphazardly removing features. In this case, removal of the region factory objects will break any other Spark codebase in the wild that depended on these factories.

Instead, I would suggest marking these factories with `@Deprecated` flag instead so library users would get a compiler warning and a sufficient time to update their code according to the README and then we can remove it and bump the major version number.

2019-04-05 18:13 UTC, Lance0312 commented
I understand the importance of semver, but this repo never really work from the beginning, so I don't think there is anyone really using this repo. Also, people should understand that there could be bc-breaking changes due to this repo still < 1.0 according to semver. Anyway, I'll see if I can mark those classes with `@deprecated`.

2019-04-05 21:29 UTC, AndrewJo approved these changes

2019-04-09 17:35 UTC, merged